__all__ = ['ENTITIES_LUMP', 'TEXTURES_LUMP', 'PLANES_LUMP', 'NODES_LUMP', 'LEAFS_LUMP', 'LEAFFACES_LUMP', 'LEAFBRUSHES_LUMP',
           'MODELS_LUMP', 'BRUSHES_LUMP', 'BRUSHSIDES_LUMP', 'VERTEXES_LUMP', 'MESHVERTS_LUMP', 'EFFECTS_LUMP', 'FACES_LUMP',
           'LIGHTMAPS_LUMP', 'LIGHTVOLS_LUMP', 'VISDATA_LUMP', 'CHAR_ENCODING']

# %% [Lumps]

ENTITIES_LUMP = 0
TEXTURES_LUMP = 1
PLANES_LUMP = 2
NODES_LUMP = 3
LEAFS_LUMP = 4
LEAFFACES_LUMP = 5
LEAFBRUSHES_LUMP = 6
MODELS_LUMP = 7
BRUSHES_LUMP = 8
BRUSHSIDES_LUMP = 9
VERTEXES_LUMP = 10
MESHVERTS_LUMP = 11
EFFECTS_LUMP = 12
FACES_LUMP = 13
LIGHTMAPS_LUMP = 14
LIGHTVOLS_LUMP = 15
VISDATA_LUMP = 16

# %% [Globals]
CHAR_ENCODING = 'ascii'
